import { createClient } from "@sanity/client";
import * as dotenv from "dotenv";
import * as path from "node:path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const SANITY_PROJECT_ID =
  process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "fhp2b1rf";
const SANITY_DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";
const SANITY_TOKEN = process.env.NEXT_PUBLIC_SANITY_API_TOKEN;

if (!SANITY_TOKEN) {
  console.error(
    "❌  NEXT_PUBLIC_SANITY_API_TOKEN is missing from .env.local. Aborting.",
  );
  process.exit(1);
}

const sanity = createClient({
  projectId: SANITY_PROJECT_ID,
  dataset: SANITY_DATASET,
  apiVersion: "2024-01-01",
  token: SANITY_TOKEN,
  useCdn: false,
});

const ALLOWED_BRANDS = [
  "Audi",
  "Aion",
  "AITO",
  "Avatr",
  "ARCFOX",
  "Alfa Romeo",
  "Aston Martin",
  "Acura",
  "Aiways",
  "AUXUN",
  "ALPINA",
  "AM XIAOAO",
  "AnKai",
  "ARMADILLO",
  "BYD",
  "BMW",
  "Buick",
  "BaoJun",
  "Bestune",
  "BAW",
  "Beijing",
  "BeiJing Auto",
  "Brilliance Auto",
  "BAIC BJEV",
  "Bentley",
  "Borgward",
  "BAIC ChangHe",
  "BAIC Hyosow",
  "BAIC WeiWang",
  "BiSu",
  "Brabus",
  "BAIC RuiXiang",
  "BiKe",
  "BaiZhi",
  "Bufite",
  "ChangAn",
  "Chevrolet",
  "Chery",
  "Cadillac",
  "ChangAn QiYuan",
  "Citroen",
  "ChangAn Oshan",
  "Chery EV",
  "ChangAn Kaicene",
  "ChangAn KuaYue",
  "Chrysler",
  "Ciimo",
  "Cyberspace",
  "CHEVOO",
  "Century",
  "ChengShi",
  "CAVAN",
  "CHTC",
  "Carlsson",
  "Cenntro",
  "Chery Wanda",
  "Denza",
  "Deepal",
  "DongFeng Aeolus",
  "Dongfeng",
  "DongFeng eπ",
  "DongFeng Forthing",
  "DongFeng Fengon",
  "DongFeng FuKang",
  "DongFeng DFAC",
  "DS",
  "DongFeng DFSK",
  "Dodge",
  "DaYun",
  "DongFeng FengDu",
  "Dorcen",
  "Dearcc",
  "Exceed",
  "Everus",
  "Enovate",
  "Enranger",
  "EV House",
  "Ford",
  "FangChengBao",
  "Foton",
  "Fulwin",
  "Ferrari",
  "Firefly",
  "FAW",
  "Fiat",
  "Foday",
  "FHA",
  "FeiDi",
  "Geely",
  "GAC Trumpchi",
  "Geely Galaxy",
  "Geometry",
  "Great Wall",
  "GAC",
  "Golden Dragon",
  "GMC",
  "Genesis",
  "GuoJi",
  "Gleagle",
  "George Patton",
  "GAC Gonow",
  "Honda",
  "Haval",
  "Hyundai",
  "HongQi",
  "HaiMa",
  "HYPTEC",
  "HanTeng",
  "HIMA",
  "Hycan",
  "HiPhi",
  "HuangHai",
  "HawTai",
  "Hunkt",
  "Hummer",
  "HuaSong",
  "HEDMOS",
  "Hafei Motor",
  "HuaTai",
  "HuaChenXinRi",
  "Higer",
  "HuaKai",
  "HengChi",
  "Horki",
  "HuaZi Auto",
  "IM",
  "Isuzu",
  "Infiniti",
  "Iveco",
  "iCAR",
  "Jetour",
  "Jetta",
  "Jeep",
  "Jaguar",
  "Jetour ShanHai",
  "JAC",
  "JMC",
  "JinBei",
  "JAC Refine",
  "JMEV",
  "JiYue",
  "Jetour Zongheng",
  "Jenhoo",
  "JDMC",
  "JunTian",
  "Joylong",
  "Jonway",
  "JiangNan",
  "JMMC",
  "Jingfei Automobile",
  "Kia",
  "Karry",
  "KaiYi",
  "KingLong",
  "Kede",
  "Kama",
  "Kawe Auto",
  "KaSheng",
  "Kmuller",
  "Land Rover",
  "Li",
  "LYNK&CO",
  "Lincoln",
  "Lexus",
  "Leapmotor",
  "Lamborghini",
  "Livan",
  "Levdeo",
  "LiFan",
  "Landwind",
  "Luxgen",
  "LingBox",
  "Luxeed",
  "Leopaard",
  "LanDian",
  "Lotus",
  "Lorinser",
  "LUMMA",
  "LinkTour",
  "Linxys",
  "LEVC",
  "Langsi",
  "Lark",
  "LITE",
  "Mercedes-Benz",
  "Mazda",
  "MG",
  "MI",
  "MAXUS",
  "Maserati",
  "Mitsubishi",
  "MINI",
  "McLaren",
  "Mansory",
  "M Hero",
  "MAEXTRO",
  "Morgan",
  "Modern Auto",
  "MaiMai",
  "Nissan",
  "NIO",
  "Neta",
  "NLM Motor",
  "New Gonow",
  "Neomor",
  "Ora",
  "ONVO",
  "Opel",
  "Oley",
  "Obbin",
  "Peugeot",
  "Porsche",
  "Polestar",
  "Pocco",
  "Qoros",
  "QianTu",
  "Roewe",
  "Rolls-Royce",
  "Renault",
  "Ruichi Auto",
  "ROX",
  "ROXROX",
  "Radar",
  "RAM",
  "Riich",
  "Reach",
  "ROXPloeStone",
  "Rely",
  "Rhine Auto",
  "Skoda",
  "Subaru",
  "Suzuki",
  "Smart",
  "Skyworth",
  "Soueast",
  "Sehol",
  "Stelato",
  "SWM",
  "SERES",
  "ShenZhou",
  "Shenzer",
  "SRM",
  "SionGold",
  "ShangJie",
  "SsangYong",
  "Saleen",
  "SONGSAN MOTORS",
  "SunLong",
  "Seat",
  "SinoTruck VGV",
  "Saab",
  "Startech",
  "Sitech",
  "SHELBY",
  "ShuangHuan",
  "Skywell",
  "Speed Auto",
  "SuDa",
  "ShengTang",
  "Toyota",
  "Tesla",
  "Tank",
  "The Durant Guild",
  "Traum",
  "TaiRuiTe",
  "TongJia",
  "TECHART",
  "Volkswagen",
  "Volvo",
  "Voyah",
  "Venucia",
  "VGV",
  "Victory Auto",
  "Vulcanus",
  "WuLing",
  "WEY",
  "Weltmeister",
  "Wowsen",
  "WanXiang",
  "WinnerWay",
  "Xpeng",
  "XiaoHu EV",
  "Xinkai",
  "XingHaiShi",
  "YangWang",
  "Yudo",
  "Yema",
  "YuanChen",
  "Yufeng Auto",
  "YuTong",
  "YuanHang",
  "YaSheng",
  "Yuejin",
  "Zeekr",
  "Zotye",
  "ZD",
  "ZX AUTO",
  "Zedriv",
  "Zinoro",
];

async function main() {
  console.log("🔎  Fetching all `brand` documents from Sanity...");

  const brands = await sanity.fetch<{ _id: string; title: string }[]>(
    '*[_type == "brand"]{ _id, title }',
  );

  if (brands.length === 0) {
    console.log("  → No brand documents found.");
    return;
  }

  const toDelete = brands.filter(
    (b) => !ALLOWED_BRANDS.includes(b.title?.trim()),
  );

  if (toDelete.length === 0) {
    console.log("  → All brand titles are in the whitelist. Nothing to delete.");
    return;
  }

  console.log(
    `  → Attempting to delete ${toDelete.length} non-whitelisted brands:\n` +
      toDelete.map((b) => `    - ${b.title} (${b._id})`).join("\n"),
  );

  let deleted = 0;
  let skipped = 0;

  for (const b of toDelete) {
    try {
      await sanity.delete(b._id);
      deleted += 1;
    } catch (error: any) {
      skipped += 1;
      const message =
        typeof error?.message === "string"
          ? error.message
          : JSON.stringify(error?.details ?? error);
      console.warn(
        `  ⚠️  Skipped deleting brand "${b.title}" (${b._id}) due to references or other error:\n      ${message}`,
      );
    }
  }

  console.log(
    `  ✅ Finished. Deleted ${deleted} brand documents, skipped ${skipped} (likely still referenced).`,
  );
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});

